#!/usr/bin/env python3
"""Check that every user story and requirement is accounted for in the architecture.

The point is not bureaucracy: an uncovered story usually means a capability nobody
designed for, and a dangling ID usually means a typo that quietly breaks the audit
trail between the backlog and the design.

Usage:
    python3 check_coverage.py --stories backlog/ --arch docs/architecture/
    python3 check_coverage.py --stories backlog/ --arch docs/ --matrix docs/architecture/traceability.md

Exit code is 1 when something is uncovered or dangling, so it can gate a review.
"""

import argparse
import re
import sys
from datetime import date
from pathlib import Path

ID = re.compile(r"\b((?:US|FR|NFR|EP)-\d+)\b")
ADR_REF = re.compile(r"\b(ADR-\d+)\b")
DEFINES = re.compile(r"^\s*(?:#{1,6}\s*|\|\s*|[-*]\s*|\*\*)?((?:US|FR|NFR|EP)-\d+)\b")


def md_files(root):
    p = Path(root)
    if p.is_file():
        return [p]
    return sorted(q for q in p.rglob("*.md") if "node_modules" not in q.parts)


def collect(paths, pattern=ID):
    """Return {id: set(files)} for every ID mentioned in the given files."""
    found = {}
    for f in paths:
        for m in pattern.finditer(f.read_text(encoding="utf-8", errors="replace")):
            found.setdefault(m.group(1), set()).add(f)
    return found


def declared(paths):
    """IDs that a file appears to *define* (heading, table row start, list item, filename)."""
    out = {}
    for f in paths:
        m = DEFINES.match(f.stem.upper().replace("_", "-"))
        if m:
            out.setdefault(m.group(1), set()).add(f)
        for line in f.read_text(encoding="utf-8", errors="replace").splitlines():
            m = DEFINES.match(line)
            if m:
                out.setdefault(m.group(1), set()).add(f)
    return out


def main():
    ap = argparse.ArgumentParser(description="Story-to-architecture coverage check.")
    ap.add_argument("--stories", required=True, help="Backlog file or directory (US/FR/NFR source)")
    ap.add_argument("--arch", required=True, help="Architecture doc file or directory")
    ap.add_argument("--matrix", help="Write a coverage matrix to this markdown path")
    ap.add_argument("--ignore", default="", help="Comma-separated IDs to exclude (e.g. out of scope)")
    args = ap.parse_args()

    story_files, arch_files = md_files(args.stories), md_files(args.arch)
    if not story_files:
        print(f"No markdown found under {args.stories}", file=sys.stderr)
        return 2
    if not arch_files:
        print(f"No markdown found under {args.arch}", file=sys.stderr)
        return 2

    ignored = {s.strip().upper() for s in args.ignore.split(",") if s.strip()}
    backlog = {k: v for k, v in declared(story_files).items() if k not in ignored}
    if not backlog:
        backlog = {k: v for k, v in collect(story_files).items() if k not in ignored}
    in_arch = collect(arch_files)

    uncovered = sorted(k for k in backlog if k not in in_arch)
    dangling = sorted(k for k in in_arch if k not in backlog and k not in ignored)

    adrs_defined = set()
    for f in arch_files:
        m = ADR_REF.match(f.stem.upper())
        if m:
            adrs_defined.add(m.group(1))
        for line in f.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.startswith("#"):
                adrs_defined |= set(ADR_REF.findall(line))
    adrs_referenced = set(collect(arch_files, ADR_REF))
    missing_adrs = sorted(adrs_referenced - adrs_defined)

    print(f"Backlog IDs found:      {len(backlog)}")
    print(f"Referenced in design:   {len(set(backlog) & set(in_arch))}")
    if uncovered:
        print(f"\nNOT addressed anywhere in the architecture ({len(uncovered)}):")
        for k in uncovered:
            print(f"  {k}")
    if dangling:
        print(f"\nReferenced in the design but not in the backlog ({len(dangling)}) — typo or missing story:")
        for k in dangling:
            print(f"  {k}  (in {', '.join(sorted(str(p) for p in in_arch[k]))})")
    if missing_adrs:
        print(f"\nADRs referenced but not written ({len(missing_adrs)}): {', '.join(missing_adrs)}")
    if not (uncovered or dangling or missing_adrs):
        print("\nAll backlog IDs are addressed and all references resolve.")

    if args.matrix:
        rows = ["---", "id: TRACE-001", "type: generated", "status: generated",
                f"reviewed: {date.today().isoformat()}", "owner: generated-by-script",
                "---", "", "# Traceability matrix", "",
                "Generated by `check_coverage.py`. Each row links a backlog item to the "
                "part of the design that satisfies it.", "",
                "| ID | Addressed in |", "|---|---|"]
        for k in sorted(backlog, key=lambda s: (s.split("-")[0], int(s.split("-")[1]))):
            where = ", ".join(f"`{p.name}`" for p in sorted(in_arch.get(k, []))) or "**not addressed**"
            rows.append(f"| {k} | {where} |")
        Path(args.matrix).parent.mkdir(parents=True, exist_ok=True)
        Path(args.matrix).write_text("\n".join(rows) + "\n", encoding="utf-8")
        print(f"\nMatrix written to {args.matrix}")

    return 1 if (uncovered or dangling or missing_adrs) else 0


if __name__ == "__main__":
    sys.exit(main())
